# -*- coding: utf-8 -*-
"""removeDuplicates.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfpVbnqNehilUzK8SAixsdxVcjbnYpO7
"""

class Solution:
    def removeDuplicates(self, nums: list[int]) -> int:
      #2 указателя. первый будет находиться на месте, куда ставить новый уникальный элемент. второй будет ходить по списку и искать уникальные элементы
        j=0
        for i in range(1,len(nums),1):
            if nums[j]!=nums[i]:
                j+=1
                nums[j]=nums[i]
        return j+1

