# -*- coding: utf-8 -*-
"""tinkof first1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_lUjI4VOitgIAKBhwPJteDdapWE2jAR
"""

class Solution():

  def ListFromRe(self,re=""): #получение списка из регулярного выражения
    def isInt(s): #является ли целым числом выражение
          try:
            int(s)
            return True
          except ValueError:
            return False
    nums=set()
    for i in re.split(','):
      if isInt(i):
        nums.add(int(i))
      else:
        start,end=map(int,i.split('-'))
        for j in range(start,end+1,1):
          nums.add(j)
    return nums

exmpl1=Solution()
re1="12-23,24-25,111,123-125"
exmpl1.ListFromRe(re1)

x='123--'
def isint(x):
  try:
    return isinstance(int(x),int)
  except ValueError:
    return False
isint(x)

a="112-123"
b,c=map(int,a.split('-'))
print(type(b),c)